// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: game_proto.proto

#ifndef PROTOBUF_game_5fproto_2eproto__INCLUDED
#define PROTOBUF_game_5fproto_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3005001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace protobuf_game_5fproto_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[7];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
void InitDefaultsPositionImpl();
void InitDefaultsPosition();
void InitDefaultsPlayerInfoImpl();
void InitDefaultsPlayerInfo();
void InitDefaultsPlayerStateImpl();
void InitDefaultsPlayerState();
void InitDefaultsPlayerInputImpl();
void InitDefaultsPlayerInput();
void InitDefaultsRoomInfoImpl();
void InitDefaultsRoomInfo();
void InitDefaultsClientMsgImpl();
void InitDefaultsClientMsg();
void InitDefaultsServerMsgImpl();
void InitDefaultsServerMsg();
inline void InitDefaults() {
  InitDefaultsPosition();
  InitDefaultsPlayerInfo();
  InitDefaultsPlayerState();
  InitDefaultsPlayerInput();
  InitDefaultsRoomInfo();
  InitDefaultsClientMsg();
  InitDefaultsServerMsg();
}
}  // namespace protobuf_game_5fproto_2eproto
namespace GameProto {
class ClientMsg;
class ClientMsgDefaultTypeInternal;
extern ClientMsgDefaultTypeInternal _ClientMsg_default_instance_;
class PlayerInfo;
class PlayerInfoDefaultTypeInternal;
extern PlayerInfoDefaultTypeInternal _PlayerInfo_default_instance_;
class PlayerInput;
class PlayerInputDefaultTypeInternal;
extern PlayerInputDefaultTypeInternal _PlayerInput_default_instance_;
class PlayerState;
class PlayerStateDefaultTypeInternal;
extern PlayerStateDefaultTypeInternal _PlayerState_default_instance_;
class Position;
class PositionDefaultTypeInternal;
extern PositionDefaultTypeInternal _Position_default_instance_;
class RoomInfo;
class RoomInfoDefaultTypeInternal;
extern RoomInfoDefaultTypeInternal _RoomInfo_default_instance_;
class ServerMsg;
class ServerMsgDefaultTypeInternal;
extern ServerMsgDefaultTypeInternal _ServerMsg_default_instance_;
}  // namespace GameProto
namespace GameProto {

enum ServerEventCode {
  LogInSuccess = 0,
  RegisterSuccess = 1,
  EnterRoomSuccess = 2,
  LogInError_AccountDontExist = 3,
  LogInError_PasswordWrong = 4,
  LogInError_ReLogIn = 5,
  RegisterError_AccountAlreadyExist = 6,
  EnterRoomError_DontLogIn = 7,
  EnterRoomError_RoomIsFull = 8,
  EnterRoomError_RoomDontExit = 9,
  InternalError = 10,
  BroadRoomListInfo = 11,
  BroadRoomInfo = 12,
  JumpToBattleServer = 13,
  S2CSync = 14,
  ExitRoomSuccess = 15,
  ExitRoomError_DontLogIn = 16,
  ExitRoomError_RoomIsEmpty = 17,
  CreateRoomSuccess = 18,
  ServerEventCode_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  ServerEventCode_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool ServerEventCode_IsValid(int value);
const ServerEventCode ServerEventCode_MIN = LogInSuccess;
const ServerEventCode ServerEventCode_MAX = CreateRoomSuccess;
const int ServerEventCode_ARRAYSIZE = ServerEventCode_MAX + 1;

const ::google::protobuf::EnumDescriptor* ServerEventCode_descriptor();
inline const ::std::string& ServerEventCode_Name(ServerEventCode value) {
  return ::google::protobuf::internal::NameOfEnum(
    ServerEventCode_descriptor(), value);
}
inline bool ServerEventCode_Parse(
    const ::std::string& name, ServerEventCode* value) {
  return ::google::protobuf::internal::ParseNamedEnum<ServerEventCode>(
    ServerEventCode_descriptor(), name, value);
}
enum ClientEventCode {
  LogIn = 0,
  Regist = 1,
  CreateRoom = 2,
  EnterRoom = 3,
  ExitRoom = 4,
  C2SSync = 5,
  Follow = 6,
  ChangeStateInRoom = 7,
  StartGame = 8,
  ClientEventCode_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  ClientEventCode_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool ClientEventCode_IsValid(int value);
const ClientEventCode ClientEventCode_MIN = LogIn;
const ClientEventCode ClientEventCode_MAX = StartGame;
const int ClientEventCode_ARRAYSIZE = ClientEventCode_MAX + 1;

const ::google::protobuf::EnumDescriptor* ClientEventCode_descriptor();
inline const ::std::string& ClientEventCode_Name(ClientEventCode value) {
  return ::google::protobuf::internal::NameOfEnum(
    ClientEventCode_descriptor(), value);
}
inline bool ClientEventCode_Parse(
    const ::std::string& name, ClientEventCode* value) {
  return ::google::protobuf::internal::ParseNamedEnum<ClientEventCode>(
    ClientEventCode_descriptor(), name, value);
}
// ===================================================================

class Position : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:GameProto.Position) */ {
 public:
  Position();
  virtual ~Position();

  Position(const Position& from);

  inline Position& operator=(const Position& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  Position(Position&& from) noexcept
    : Position() {
    *this = ::std::move(from);
  }

  inline Position& operator=(Position&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const Position& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Position* internal_default_instance() {
    return reinterpret_cast<const Position*>(
               &_Position_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(Position* other);
  friend void swap(Position& a, Position& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline Position* New() const PROTOBUF_FINAL { return New(NULL); }

  Position* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const Position& from);
  void MergeFrom(const Position& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(Position* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // float x = 1;
  void clear_x();
  static const int kXFieldNumber = 1;
  float x() const;
  void set_x(float value);

  // float y = 2;
  void clear_y();
  static const int kYFieldNumber = 2;
  float y() const;
  void set_y(float value);

  // float z = 3;
  void clear_z();
  static const int kZFieldNumber = 3;
  float z() const;
  void set_z(float value);

  // @@protoc_insertion_point(class_scope:GameProto.Position)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  float x_;
  float y_;
  float z_;
  mutable int _cached_size_;
  friend struct ::protobuf_game_5fproto_2eproto::TableStruct;
  friend void ::protobuf_game_5fproto_2eproto::InitDefaultsPositionImpl();
};
// -------------------------------------------------------------------

class PlayerInfo : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:GameProto.PlayerInfo) */ {
 public:
  PlayerInfo();
  virtual ~PlayerInfo();

  PlayerInfo(const PlayerInfo& from);

  inline PlayerInfo& operator=(const PlayerInfo& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  PlayerInfo(PlayerInfo&& from) noexcept
    : PlayerInfo() {
    *this = ::std::move(from);
  }

  inline PlayerInfo& operator=(PlayerInfo&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const PlayerInfo& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const PlayerInfo* internal_default_instance() {
    return reinterpret_cast<const PlayerInfo*>(
               &_PlayerInfo_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    1;

  void Swap(PlayerInfo* other);
  friend void swap(PlayerInfo& a, PlayerInfo& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline PlayerInfo* New() const PROTOBUF_FINAL { return New(NULL); }

  PlayerInfo* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const PlayerInfo& from);
  void MergeFrom(const PlayerInfo& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(PlayerInfo* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string account = 2;
  void clear_account();
  static const int kAccountFieldNumber = 2;
  const ::std::string& account() const;
  void set_account(const ::std::string& value);
  #if LANG_CXX11
  void set_account(::std::string&& value);
  #endif
  void set_account(const char* value);
  void set_account(const char* value, size_t size);
  ::std::string* mutable_account();
  ::std::string* release_account();
  void set_allocated_account(::std::string* account);

  // string password = 3;
  void clear_password();
  static const int kPasswordFieldNumber = 3;
  const ::std::string& password() const;
  void set_password(const ::std::string& value);
  #if LANG_CXX11
  void set_password(::std::string&& value);
  #endif
  void set_password(const char* value);
  void set_password(const char* value, size_t size);
  ::std::string* mutable_password();
  ::std::string* release_password();
  void set_allocated_password(::std::string* password);

  // string nickname = 4;
  void clear_nickname();
  static const int kNicknameFieldNumber = 4;
  const ::std::string& nickname() const;
  void set_nickname(const ::std::string& value);
  #if LANG_CXX11
  void set_nickname(::std::string&& value);
  #endif
  void set_nickname(const char* value);
  void set_nickname(const char* value, size_t size);
  ::std::string* mutable_nickname();
  ::std::string* release_nickname();
  void set_allocated_nickname(::std::string* nickname);

  // int32 uid = 1;
  void clear_uid();
  static const int kUidFieldNumber = 1;
  ::google::protobuf::int32 uid() const;
  void set_uid(::google::protobuf::int32 value);

  // int32 roomid = 5;
  void clear_roomid();
  static const int kRoomidFieldNumber = 5;
  ::google::protobuf::int32 roomid() const;
  void set_roomid(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:GameProto.PlayerInfo)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr account_;
  ::google::protobuf::internal::ArenaStringPtr password_;
  ::google::protobuf::internal::ArenaStringPtr nickname_;
  ::google::protobuf::int32 uid_;
  ::google::protobuf::int32 roomid_;
  mutable int _cached_size_;
  friend struct ::protobuf_game_5fproto_2eproto::TableStruct;
  friend void ::protobuf_game_5fproto_2eproto::InitDefaultsPlayerInfoImpl();
};
// -------------------------------------------------------------------

class PlayerState : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:GameProto.PlayerState) */ {
 public:
  PlayerState();
  virtual ~PlayerState();

  PlayerState(const PlayerState& from);

  inline PlayerState& operator=(const PlayerState& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  PlayerState(PlayerState&& from) noexcept
    : PlayerState() {
    *this = ::std::move(from);
  }

  inline PlayerState& operator=(PlayerState&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const PlayerState& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const PlayerState* internal_default_instance() {
    return reinterpret_cast<const PlayerState*>(
               &_PlayerState_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    2;

  void Swap(PlayerState* other);
  friend void swap(PlayerState& a, PlayerState& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline PlayerState* New() const PROTOBUF_FINAL { return New(NULL); }

  PlayerState* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const PlayerState& from);
  void MergeFrom(const PlayerState& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(PlayerState* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string name = 2;
  void clear_name();
  static const int kNameFieldNumber = 2;
  const ::std::string& name() const;
  void set_name(const ::std::string& value);
  #if LANG_CXX11
  void set_name(::std::string&& value);
  #endif
  void set_name(const char* value);
  void set_name(const char* value, size_t size);
  ::std::string* mutable_name();
  ::std::string* release_name();
  void set_allocated_name(::std::string* name);

  // .GameProto.Position pos = 4;
  bool has_pos() const;
  void clear_pos();
  static const int kPosFieldNumber = 4;
  const ::GameProto::Position& pos() const;
  ::GameProto::Position* release_pos();
  ::GameProto::Position* mutable_pos();
  void set_allocated_pos(::GameProto::Position* pos);

  // int32 fid = 1;
  void clear_fid();
  static const int kFidFieldNumber = 1;
  ::google::protobuf::int32 fid() const;
  void set_fid(::google::protobuf::int32 value);

  // float yaw = 3;
  void clear_yaw();
  static const int kYawFieldNumber = 3;
  float yaw() const;
  void set_yaw(float value);

  // int32 state = 5;
  void clear_state();
  static const int kStateFieldNumber = 5;
  ::google::protobuf::int32 state() const;
  void set_state(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:GameProto.PlayerState)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr name_;
  ::GameProto::Position* pos_;
  ::google::protobuf::int32 fid_;
  float yaw_;
  ::google::protobuf::int32 state_;
  mutable int _cached_size_;
  friend struct ::protobuf_game_5fproto_2eproto::TableStruct;
  friend void ::protobuf_game_5fproto_2eproto::InitDefaultsPlayerStateImpl();
};
// -------------------------------------------------------------------

class PlayerInput : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:GameProto.PlayerInput) */ {
 public:
  PlayerInput();
  virtual ~PlayerInput();

  PlayerInput(const PlayerInput& from);

  inline PlayerInput& operator=(const PlayerInput& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  PlayerInput(PlayerInput&& from) noexcept
    : PlayerInput() {
    *this = ::std::move(from);
  }

  inline PlayerInput& operator=(PlayerInput&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const PlayerInput& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const PlayerInput* internal_default_instance() {
    return reinterpret_cast<const PlayerInput*>(
               &_PlayerInput_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    3;

  void Swap(PlayerInput* other);
  friend void swap(PlayerInput& a, PlayerInput& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline PlayerInput* New() const PROTOBUF_FINAL { return New(NULL); }

  PlayerInput* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const PlayerInput& from);
  void MergeFrom(const PlayerInput& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(PlayerInput* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // int64 headTowardsX = 1;
  void clear_headtowardsx();
  static const int kHeadTowardsXFieldNumber = 1;
  ::google::protobuf::int64 headtowardsx() const;
  void set_headtowardsx(::google::protobuf::int64 value);

  // int64 headTowardsY = 2;
  void clear_headtowardsy();
  static const int kHeadTowardsYFieldNumber = 2;
  ::google::protobuf::int64 headtowardsy() const;
  void set_headtowardsy(::google::protobuf::int64 value);

  // int64 headTowardsZ = 3;
  void clear_headtowardsz();
  static const int kHeadTowardsZFieldNumber = 3;
  ::google::protobuf::int64 headtowardsz() const;
  void set_headtowardsz(::google::protobuf::int64 value);

  // int64 moveDirectionX = 4;
  void clear_movedirectionx();
  static const int kMoveDirectionXFieldNumber = 4;
  ::google::protobuf::int64 movedirectionx() const;
  void set_movedirectionx(::google::protobuf::int64 value);

  // int64 moveDirectionY = 5;
  void clear_movedirectiony();
  static const int kMoveDirectionYFieldNumber = 5;
  ::google::protobuf::int64 movedirectiony() const;
  void set_movedirectiony(::google::protobuf::int64 value);

  // int32 usePropsInPackID = 6;
  void clear_usepropsinpackid();
  static const int kUsePropsInPackIDFieldNumber = 6;
  ::google::protobuf::int32 usepropsinpackid() const;
  void set_usepropsinpackid(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:GameProto.PlayerInput)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::int64 headtowardsx_;
  ::google::protobuf::int64 headtowardsy_;
  ::google::protobuf::int64 headtowardsz_;
  ::google::protobuf::int64 movedirectionx_;
  ::google::protobuf::int64 movedirectiony_;
  ::google::protobuf::int32 usepropsinpackid_;
  mutable int _cached_size_;
  friend struct ::protobuf_game_5fproto_2eproto::TableStruct;
  friend void ::protobuf_game_5fproto_2eproto::InitDefaultsPlayerInputImpl();
};
// -------------------------------------------------------------------

class RoomInfo : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:GameProto.RoomInfo) */ {
 public:
  RoomInfo();
  virtual ~RoomInfo();

  RoomInfo(const RoomInfo& from);

  inline RoomInfo& operator=(const RoomInfo& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  RoomInfo(RoomInfo&& from) noexcept
    : RoomInfo() {
    *this = ::std::move(from);
  }

  inline RoomInfo& operator=(RoomInfo&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const RoomInfo& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const RoomInfo* internal_default_instance() {
    return reinterpret_cast<const RoomInfo*>(
               &_RoomInfo_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    4;

  void Swap(RoomInfo* other);
  friend void swap(RoomInfo& a, RoomInfo& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline RoomInfo* New() const PROTOBUF_FINAL { return New(NULL); }

  RoomInfo* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const RoomInfo& from);
  void MergeFrom(const RoomInfo& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(RoomInfo* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .GameProto.PlayerInfo preparedPlayers = 9;
  int preparedplayers_size() const;
  void clear_preparedplayers();
  static const int kPreparedPlayersFieldNumber = 9;
  const ::GameProto::PlayerInfo& preparedplayers(int index) const;
  ::GameProto::PlayerInfo* mutable_preparedplayers(int index);
  ::GameProto::PlayerInfo* add_preparedplayers();
  ::google::protobuf::RepeatedPtrField< ::GameProto::PlayerInfo >*
      mutable_preparedplayers();
  const ::google::protobuf::RepeatedPtrField< ::GameProto::PlayerInfo >&
      preparedplayers() const;

  // repeated .GameProto.PlayerInfo unPreparedPlayers = 10;
  int unpreparedplayers_size() const;
  void clear_unpreparedplayers();
  static const int kUnPreparedPlayersFieldNumber = 10;
  const ::GameProto::PlayerInfo& unpreparedplayers(int index) const;
  ::GameProto::PlayerInfo* mutable_unpreparedplayers(int index);
  ::GameProto::PlayerInfo* add_unpreparedplayers();
  ::google::protobuf::RepeatedPtrField< ::GameProto::PlayerInfo >*
      mutable_unpreparedplayers();
  const ::google::protobuf::RepeatedPtrField< ::GameProto::PlayerInfo >&
      unpreparedplayers() const;

  // string roomName = 4;
  void clear_roomname();
  static const int kRoomNameFieldNumber = 4;
  const ::std::string& roomname() const;
  void set_roomname(const ::std::string& value);
  #if LANG_CXX11
  void set_roomname(::std::string&& value);
  #endif
  void set_roomname(const char* value);
  void set_roomname(const char* value, size_t size);
  ::std::string* mutable_roomname();
  ::std::string* release_roomname();
  void set_allocated_roomname(::std::string* roomname);

  // string mapName = 5;
  void clear_mapname();
  static const int kMapNameFieldNumber = 5;
  const ::std::string& mapname() const;
  void set_mapname(const ::std::string& value);
  #if LANG_CXX11
  void set_mapname(::std::string&& value);
  #endif
  void set_mapname(const char* value);
  void set_mapname(const char* value, size_t size);
  ::std::string* mutable_mapname();
  ::std::string* release_mapname();
  void set_allocated_mapname(::std::string* mapname);

  // string password = 6;
  void clear_password();
  static const int kPasswordFieldNumber = 6;
  const ::std::string& password() const;
  void set_password(const ::std::string& value);
  #if LANG_CXX11
  void set_password(::std::string&& value);
  #endif
  void set_password(const char* value);
  void set_password(const char* value, size_t size);
  ::std::string* mutable_password();
  ::std::string* release_password();
  void set_allocated_password(::std::string* password);

  // int32 id = 1;
  void clear_id();
  static const int kIdFieldNumber = 1;
  ::google::protobuf::int32 id() const;
  void set_id(::google::protobuf::int32 value);

  // int32 roundTime = 2;
  void clear_roundtime();
  static const int kRoundTimeFieldNumber = 2;
  ::google::protobuf::int32 roundtime() const;
  void set_roundtime(::google::protobuf::int32 value);

  // int32 roundNumber = 3;
  void clear_roundnumber();
  static const int kRoundNumberFieldNumber = 3;
  ::google::protobuf::int32 roundnumber() const;
  void set_roundnumber(::google::protobuf::int32 value);

  // int32 maxPlayers = 7;
  void clear_maxplayers();
  static const int kMaxPlayersFieldNumber = 7;
  ::google::protobuf::int32 maxplayers() const;
  void set_maxplayers(::google::protobuf::int32 value);

  // int32 curPlayerNumber = 8;
  void clear_curplayernumber();
  static const int kCurPlayerNumberFieldNumber = 8;
  ::google::protobuf::int32 curplayernumber() const;
  void set_curplayernumber(::google::protobuf::int32 value);

  // int32 master = 11;
  void clear_master();
  static const int kMasterFieldNumber = 11;
  ::google::protobuf::int32 master() const;
  void set_master(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:GameProto.RoomInfo)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::GameProto::PlayerInfo > preparedplayers_;
  ::google::protobuf::RepeatedPtrField< ::GameProto::PlayerInfo > unpreparedplayers_;
  ::google::protobuf::internal::ArenaStringPtr roomname_;
  ::google::protobuf::internal::ArenaStringPtr mapname_;
  ::google::protobuf::internal::ArenaStringPtr password_;
  ::google::protobuf::int32 id_;
  ::google::protobuf::int32 roundtime_;
  ::google::protobuf::int32 roundnumber_;
  ::google::protobuf::int32 maxplayers_;
  ::google::protobuf::int32 curplayernumber_;
  ::google::protobuf::int32 master_;
  mutable int _cached_size_;
  friend struct ::protobuf_game_5fproto_2eproto::TableStruct;
  friend void ::protobuf_game_5fproto_2eproto::InitDefaultsRoomInfoImpl();
};
// -------------------------------------------------------------------

class ClientMsg : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:GameProto.ClientMsg) */ {
 public:
  ClientMsg();
  virtual ~ClientMsg();

  ClientMsg(const ClientMsg& from);

  inline ClientMsg& operator=(const ClientMsg& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  ClientMsg(ClientMsg&& from) noexcept
    : ClientMsg() {
    *this = ::std::move(from);
  }

  inline ClientMsg& operator=(ClientMsg&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const ClientMsg& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ClientMsg* internal_default_instance() {
    return reinterpret_cast<const ClientMsg*>(
               &_ClientMsg_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    5;

  void Swap(ClientMsg* other);
  friend void swap(ClientMsg& a, ClientMsg& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline ClientMsg* New() const PROTOBUF_FINAL { return New(NULL); }

  ClientMsg* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const ClientMsg& from);
  void MergeFrom(const ClientMsg& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(ClientMsg* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // .GameProto.PlayerInfo playerinfo = 2;
  bool has_playerinfo() const;
  void clear_playerinfo();
  static const int kPlayerinfoFieldNumber = 2;
  const ::GameProto::PlayerInfo& playerinfo() const;
  ::GameProto::PlayerInfo* release_playerinfo();
  ::GameProto::PlayerInfo* mutable_playerinfo();
  void set_allocated_playerinfo(::GameProto::PlayerInfo* playerinfo);

  // .GameProto.PlayerInput input = 3;
  bool has_input() const;
  void clear_input();
  static const int kInputFieldNumber = 3;
  const ::GameProto::PlayerInput& input() const;
  ::GameProto::PlayerInput* release_input();
  ::GameProto::PlayerInput* mutable_input();
  void set_allocated_input(::GameProto::PlayerInput* input);

  // .GameProto.RoomInfo roominfo = 4;
  bool has_roominfo() const;
  void clear_roominfo();
  static const int kRoominfoFieldNumber = 4;
  const ::GameProto::RoomInfo& roominfo() const;
  ::GameProto::RoomInfo* release_roominfo();
  ::GameProto::RoomInfo* mutable_roominfo();
  void set_allocated_roominfo(::GameProto::RoomInfo* roominfo);

  // .GameProto.ClientEventCode type = 1;
  void clear_type();
  static const int kTypeFieldNumber = 1;
  ::GameProto::ClientEventCode type() const;
  void set_type(::GameProto::ClientEventCode value);

  // @@protoc_insertion_point(class_scope:GameProto.ClientMsg)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::GameProto::PlayerInfo* playerinfo_;
  ::GameProto::PlayerInput* input_;
  ::GameProto::RoomInfo* roominfo_;
  int type_;
  mutable int _cached_size_;
  friend struct ::protobuf_game_5fproto_2eproto::TableStruct;
  friend void ::protobuf_game_5fproto_2eproto::InitDefaultsClientMsgImpl();
};
// -------------------------------------------------------------------

class ServerMsg : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:GameProto.ServerMsg) */ {
 public:
  ServerMsg();
  virtual ~ServerMsg();

  ServerMsg(const ServerMsg& from);

  inline ServerMsg& operator=(const ServerMsg& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  ServerMsg(ServerMsg&& from) noexcept
    : ServerMsg() {
    *this = ::std::move(from);
  }

  inline ServerMsg& operator=(ServerMsg&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const ServerMsg& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ServerMsg* internal_default_instance() {
    return reinterpret_cast<const ServerMsg*>(
               &_ServerMsg_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    6;

  void Swap(ServerMsg* other);
  friend void swap(ServerMsg& a, ServerMsg& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline ServerMsg* New() const PROTOBUF_FINAL { return New(NULL); }

  ServerMsg* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const ServerMsg& from);
  void MergeFrom(const ServerMsg& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(ServerMsg* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .GameProto.PlayerInput inputs = 6;
  int inputs_size() const;
  void clear_inputs();
  static const int kInputsFieldNumber = 6;
  const ::GameProto::PlayerInput& inputs(int index) const;
  ::GameProto::PlayerInput* mutable_inputs(int index);
  ::GameProto::PlayerInput* add_inputs();
  ::google::protobuf::RepeatedPtrField< ::GameProto::PlayerInput >*
      mutable_inputs();
  const ::google::protobuf::RepeatedPtrField< ::GameProto::PlayerInput >&
      inputs() const;

  // repeated .GameProto.PlayerState states = 7;
  int states_size() const;
  void clear_states();
  static const int kStatesFieldNumber = 7;
  const ::GameProto::PlayerState& states(int index) const;
  ::GameProto::PlayerState* mutable_states(int index);
  ::GameProto::PlayerState* add_states();
  ::google::protobuf::RepeatedPtrField< ::GameProto::PlayerState >*
      mutable_states();
  const ::google::protobuf::RepeatedPtrField< ::GameProto::PlayerState >&
      states() const;

  // repeated .GameProto.RoomInfo roominfos = 8;
  int roominfos_size() const;
  void clear_roominfos();
  static const int kRoominfosFieldNumber = 8;
  const ::GameProto::RoomInfo& roominfos(int index) const;
  ::GameProto::RoomInfo* mutable_roominfos(int index);
  ::GameProto::RoomInfo* add_roominfos();
  ::google::protobuf::RepeatedPtrField< ::GameProto::RoomInfo >*
      mutable_roominfos();
  const ::google::protobuf::RepeatedPtrField< ::GameProto::RoomInfo >&
      roominfos() const;

  // string str = 3;
  void clear_str();
  static const int kStrFieldNumber = 3;
  const ::std::string& str() const;
  void set_str(const ::std::string& value);
  #if LANG_CXX11
  void set_str(::std::string&& value);
  #endif
  void set_str(const char* value);
  void set_str(const char* value, size_t size);
  ::std::string* mutable_str();
  ::std::string* release_str();
  void set_allocated_str(::std::string* str);

  // .GameProto.PlayerInfo playerInfo = 4;
  bool has_playerinfo() const;
  void clear_playerinfo();
  static const int kPlayerInfoFieldNumber = 4;
  const ::GameProto::PlayerInfo& playerinfo() const;
  ::GameProto::PlayerInfo* release_playerinfo();
  ::GameProto::PlayerInfo* mutable_playerinfo();
  void set_allocated_playerinfo(::GameProto::PlayerInfo* playerinfo);

  // .GameProto.ServerEventCode type = 1;
  void clear_type();
  static const int kTypeFieldNumber = 1;
  ::GameProto::ServerEventCode type() const;
  void set_type(::GameProto::ServerEventCode value);

  // int32 fid = 2;
  void clear_fid();
  static const int kFidFieldNumber = 2;
  ::google::protobuf::int32 fid() const;
  void set_fid(::google::protobuf::int32 value);

  // int32 framID = 5;
  void clear_framid();
  static const int kFramIDFieldNumber = 5;
  ::google::protobuf::int32 framid() const;
  void set_framid(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:GameProto.ServerMsg)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::GameProto::PlayerInput > inputs_;
  ::google::protobuf::RepeatedPtrField< ::GameProto::PlayerState > states_;
  ::google::protobuf::RepeatedPtrField< ::GameProto::RoomInfo > roominfos_;
  ::google::protobuf::internal::ArenaStringPtr str_;
  ::GameProto::PlayerInfo* playerinfo_;
  int type_;
  ::google::protobuf::int32 fid_;
  ::google::protobuf::int32 framid_;
  mutable int _cached_size_;
  friend struct ::protobuf_game_5fproto_2eproto::TableStruct;
  friend void ::protobuf_game_5fproto_2eproto::InitDefaultsServerMsgImpl();
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Position

// float x = 1;
inline void Position::clear_x() {
  x_ = 0;
}
inline float Position::x() const {
  // @@protoc_insertion_point(field_get:GameProto.Position.x)
  return x_;
}
inline void Position::set_x(float value) {
  
  x_ = value;
  // @@protoc_insertion_point(field_set:GameProto.Position.x)
}

// float y = 2;
inline void Position::clear_y() {
  y_ = 0;
}
inline float Position::y() const {
  // @@protoc_insertion_point(field_get:GameProto.Position.y)
  return y_;
}
inline void Position::set_y(float value) {
  
  y_ = value;
  // @@protoc_insertion_point(field_set:GameProto.Position.y)
}

// float z = 3;
inline void Position::clear_z() {
  z_ = 0;
}
inline float Position::z() const {
  // @@protoc_insertion_point(field_get:GameProto.Position.z)
  return z_;
}
inline void Position::set_z(float value) {
  
  z_ = value;
  // @@protoc_insertion_point(field_set:GameProto.Position.z)
}

// -------------------------------------------------------------------

// PlayerInfo

// int32 uid = 1;
inline void PlayerInfo::clear_uid() {
  uid_ = 0;
}
inline ::google::protobuf::int32 PlayerInfo::uid() const {
  // @@protoc_insertion_point(field_get:GameProto.PlayerInfo.uid)
  return uid_;
}
inline void PlayerInfo::set_uid(::google::protobuf::int32 value) {
  
  uid_ = value;
  // @@protoc_insertion_point(field_set:GameProto.PlayerInfo.uid)
}

// string account = 2;
inline void PlayerInfo::clear_account() {
  account_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& PlayerInfo::account() const {
  // @@protoc_insertion_point(field_get:GameProto.PlayerInfo.account)
  return account_.GetNoArena();
}
inline void PlayerInfo::set_account(const ::std::string& value) {
  
  account_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:GameProto.PlayerInfo.account)
}
#if LANG_CXX11
inline void PlayerInfo::set_account(::std::string&& value) {
  
  account_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:GameProto.PlayerInfo.account)
}
#endif
inline void PlayerInfo::set_account(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  account_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:GameProto.PlayerInfo.account)
}
inline void PlayerInfo::set_account(const char* value, size_t size) {
  
  account_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:GameProto.PlayerInfo.account)
}
inline ::std::string* PlayerInfo::mutable_account() {
  
  // @@protoc_insertion_point(field_mutable:GameProto.PlayerInfo.account)
  return account_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* PlayerInfo::release_account() {
  // @@protoc_insertion_point(field_release:GameProto.PlayerInfo.account)
  
  return account_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void PlayerInfo::set_allocated_account(::std::string* account) {
  if (account != NULL) {
    
  } else {
    
  }
  account_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), account);
  // @@protoc_insertion_point(field_set_allocated:GameProto.PlayerInfo.account)
}

// string password = 3;
inline void PlayerInfo::clear_password() {
  password_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& PlayerInfo::password() const {
  // @@protoc_insertion_point(field_get:GameProto.PlayerInfo.password)
  return password_.GetNoArena();
}
inline void PlayerInfo::set_password(const ::std::string& value) {
  
  password_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:GameProto.PlayerInfo.password)
}
#if LANG_CXX11
inline void PlayerInfo::set_password(::std::string&& value) {
  
  password_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:GameProto.PlayerInfo.password)
}
#endif
inline void PlayerInfo::set_password(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  password_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:GameProto.PlayerInfo.password)
}
inline void PlayerInfo::set_password(const char* value, size_t size) {
  
  password_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:GameProto.PlayerInfo.password)
}
inline ::std::string* PlayerInfo::mutable_password() {
  
  // @@protoc_insertion_point(field_mutable:GameProto.PlayerInfo.password)
  return password_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* PlayerInfo::release_password() {
  // @@protoc_insertion_point(field_release:GameProto.PlayerInfo.password)
  
  return password_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void PlayerInfo::set_allocated_password(::std::string* password) {
  if (password != NULL) {
    
  } else {
    
  }
  password_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), password);
  // @@protoc_insertion_point(field_set_allocated:GameProto.PlayerInfo.password)
}

// string nickname = 4;
inline void PlayerInfo::clear_nickname() {
  nickname_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& PlayerInfo::nickname() const {
  // @@protoc_insertion_point(field_get:GameProto.PlayerInfo.nickname)
  return nickname_.GetNoArena();
}
inline void PlayerInfo::set_nickname(const ::std::string& value) {
  
  nickname_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:GameProto.PlayerInfo.nickname)
}
#if LANG_CXX11
inline void PlayerInfo::set_nickname(::std::string&& value) {
  
  nickname_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:GameProto.PlayerInfo.nickname)
}
#endif
inline void PlayerInfo::set_nickname(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  nickname_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:GameProto.PlayerInfo.nickname)
}
inline void PlayerInfo::set_nickname(const char* value, size_t size) {
  
  nickname_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:GameProto.PlayerInfo.nickname)
}
inline ::std::string* PlayerInfo::mutable_nickname() {
  
  // @@protoc_insertion_point(field_mutable:GameProto.PlayerInfo.nickname)
  return nickname_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* PlayerInfo::release_nickname() {
  // @@protoc_insertion_point(field_release:GameProto.PlayerInfo.nickname)
  
  return nickname_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void PlayerInfo::set_allocated_nickname(::std::string* nickname) {
  if (nickname != NULL) {
    
  } else {
    
  }
  nickname_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), nickname);
  // @@protoc_insertion_point(field_set_allocated:GameProto.PlayerInfo.nickname)
}

// int32 roomid = 5;
inline void PlayerInfo::clear_roomid() {
  roomid_ = 0;
}
inline ::google::protobuf::int32 PlayerInfo::roomid() const {
  // @@protoc_insertion_point(field_get:GameProto.PlayerInfo.roomid)
  return roomid_;
}
inline void PlayerInfo::set_roomid(::google::protobuf::int32 value) {
  
  roomid_ = value;
  // @@protoc_insertion_point(field_set:GameProto.PlayerInfo.roomid)
}

// -------------------------------------------------------------------

// PlayerState

// int32 fid = 1;
inline void PlayerState::clear_fid() {
  fid_ = 0;
}
inline ::google::protobuf::int32 PlayerState::fid() const {
  // @@protoc_insertion_point(field_get:GameProto.PlayerState.fid)
  return fid_;
}
inline void PlayerState::set_fid(::google::protobuf::int32 value) {
  
  fid_ = value;
  // @@protoc_insertion_point(field_set:GameProto.PlayerState.fid)
}

// string name = 2;
inline void PlayerState::clear_name() {
  name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& PlayerState::name() const {
  // @@protoc_insertion_point(field_get:GameProto.PlayerState.name)
  return name_.GetNoArena();
}
inline void PlayerState::set_name(const ::std::string& value) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:GameProto.PlayerState.name)
}
#if LANG_CXX11
inline void PlayerState::set_name(::std::string&& value) {
  
  name_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:GameProto.PlayerState.name)
}
#endif
inline void PlayerState::set_name(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:GameProto.PlayerState.name)
}
inline void PlayerState::set_name(const char* value, size_t size) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:GameProto.PlayerState.name)
}
inline ::std::string* PlayerState::mutable_name() {
  
  // @@protoc_insertion_point(field_mutable:GameProto.PlayerState.name)
  return name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* PlayerState::release_name() {
  // @@protoc_insertion_point(field_release:GameProto.PlayerState.name)
  
  return name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void PlayerState::set_allocated_name(::std::string* name) {
  if (name != NULL) {
    
  } else {
    
  }
  name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), name);
  // @@protoc_insertion_point(field_set_allocated:GameProto.PlayerState.name)
}

// float yaw = 3;
inline void PlayerState::clear_yaw() {
  yaw_ = 0;
}
inline float PlayerState::yaw() const {
  // @@protoc_insertion_point(field_get:GameProto.PlayerState.yaw)
  return yaw_;
}
inline void PlayerState::set_yaw(float value) {
  
  yaw_ = value;
  // @@protoc_insertion_point(field_set:GameProto.PlayerState.yaw)
}

// .GameProto.Position pos = 4;
inline bool PlayerState::has_pos() const {
  return this != internal_default_instance() && pos_ != NULL;
}
inline void PlayerState::clear_pos() {
  if (GetArenaNoVirtual() == NULL && pos_ != NULL) {
    delete pos_;
  }
  pos_ = NULL;
}
inline const ::GameProto::Position& PlayerState::pos() const {
  const ::GameProto::Position* p = pos_;
  // @@protoc_insertion_point(field_get:GameProto.PlayerState.pos)
  return p != NULL ? *p : *reinterpret_cast<const ::GameProto::Position*>(
      &::GameProto::_Position_default_instance_);
}
inline ::GameProto::Position* PlayerState::release_pos() {
  // @@protoc_insertion_point(field_release:GameProto.PlayerState.pos)
  
  ::GameProto::Position* temp = pos_;
  pos_ = NULL;
  return temp;
}
inline ::GameProto::Position* PlayerState::mutable_pos() {
  
  if (pos_ == NULL) {
    pos_ = new ::GameProto::Position;
  }
  // @@protoc_insertion_point(field_mutable:GameProto.PlayerState.pos)
  return pos_;
}
inline void PlayerState::set_allocated_pos(::GameProto::Position* pos) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete pos_;
  }
  if (pos) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      pos = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, pos, submessage_arena);
    }
    
  } else {
    
  }
  pos_ = pos;
  // @@protoc_insertion_point(field_set_allocated:GameProto.PlayerState.pos)
}

// int32 state = 5;
inline void PlayerState::clear_state() {
  state_ = 0;
}
inline ::google::protobuf::int32 PlayerState::state() const {
  // @@protoc_insertion_point(field_get:GameProto.PlayerState.state)
  return state_;
}
inline void PlayerState::set_state(::google::protobuf::int32 value) {
  
  state_ = value;
  // @@protoc_insertion_point(field_set:GameProto.PlayerState.state)
}

// -------------------------------------------------------------------

// PlayerInput

// int64 headTowardsX = 1;
inline void PlayerInput::clear_headtowardsx() {
  headtowardsx_ = GOOGLE_LONGLONG(0);
}
inline ::google::protobuf::int64 PlayerInput::headtowardsx() const {
  // @@protoc_insertion_point(field_get:GameProto.PlayerInput.headTowardsX)
  return headtowardsx_;
}
inline void PlayerInput::set_headtowardsx(::google::protobuf::int64 value) {
  
  headtowardsx_ = value;
  // @@protoc_insertion_point(field_set:GameProto.PlayerInput.headTowardsX)
}

// int64 headTowardsY = 2;
inline void PlayerInput::clear_headtowardsy() {
  headtowardsy_ = GOOGLE_LONGLONG(0);
}
inline ::google::protobuf::int64 PlayerInput::headtowardsy() const {
  // @@protoc_insertion_point(field_get:GameProto.PlayerInput.headTowardsY)
  return headtowardsy_;
}
inline void PlayerInput::set_headtowardsy(::google::protobuf::int64 value) {
  
  headtowardsy_ = value;
  // @@protoc_insertion_point(field_set:GameProto.PlayerInput.headTowardsY)
}

// int64 headTowardsZ = 3;
inline void PlayerInput::clear_headtowardsz() {
  headtowardsz_ = GOOGLE_LONGLONG(0);
}
inline ::google::protobuf::int64 PlayerInput::headtowardsz() const {
  // @@protoc_insertion_point(field_get:GameProto.PlayerInput.headTowardsZ)
  return headtowardsz_;
}
inline void PlayerInput::set_headtowardsz(::google::protobuf::int64 value) {
  
  headtowardsz_ = value;
  // @@protoc_insertion_point(field_set:GameProto.PlayerInput.headTowardsZ)
}

// int64 moveDirectionX = 4;
inline void PlayerInput::clear_movedirectionx() {
  movedirectionx_ = GOOGLE_LONGLONG(0);
}
inline ::google::protobuf::int64 PlayerInput::movedirectionx() const {
  // @@protoc_insertion_point(field_get:GameProto.PlayerInput.moveDirectionX)
  return movedirectionx_;
}
inline void PlayerInput::set_movedirectionx(::google::protobuf::int64 value) {
  
  movedirectionx_ = value;
  // @@protoc_insertion_point(field_set:GameProto.PlayerInput.moveDirectionX)
}

// int64 moveDirectionY = 5;
inline void PlayerInput::clear_movedirectiony() {
  movedirectiony_ = GOOGLE_LONGLONG(0);
}
inline ::google::protobuf::int64 PlayerInput::movedirectiony() const {
  // @@protoc_insertion_point(field_get:GameProto.PlayerInput.moveDirectionY)
  return movedirectiony_;
}
inline void PlayerInput::set_movedirectiony(::google::protobuf::int64 value) {
  
  movedirectiony_ = value;
  // @@protoc_insertion_point(field_set:GameProto.PlayerInput.moveDirectionY)
}

// int32 usePropsInPackID = 6;
inline void PlayerInput::clear_usepropsinpackid() {
  usepropsinpackid_ = 0;
}
inline ::google::protobuf::int32 PlayerInput::usepropsinpackid() const {
  // @@protoc_insertion_point(field_get:GameProto.PlayerInput.usePropsInPackID)
  return usepropsinpackid_;
}
inline void PlayerInput::set_usepropsinpackid(::google::protobuf::int32 value) {
  
  usepropsinpackid_ = value;
  // @@protoc_insertion_point(field_set:GameProto.PlayerInput.usePropsInPackID)
}

// -------------------------------------------------------------------

// RoomInfo

// int32 id = 1;
inline void RoomInfo::clear_id() {
  id_ = 0;
}
inline ::google::protobuf::int32 RoomInfo::id() const {
  // @@protoc_insertion_point(field_get:GameProto.RoomInfo.id)
  return id_;
}
inline void RoomInfo::set_id(::google::protobuf::int32 value) {
  
  id_ = value;
  // @@protoc_insertion_point(field_set:GameProto.RoomInfo.id)
}

// int32 roundTime = 2;
inline void RoomInfo::clear_roundtime() {
  roundtime_ = 0;
}
inline ::google::protobuf::int32 RoomInfo::roundtime() const {
  // @@protoc_insertion_point(field_get:GameProto.RoomInfo.roundTime)
  return roundtime_;
}
inline void RoomInfo::set_roundtime(::google::protobuf::int32 value) {
  
  roundtime_ = value;
  // @@protoc_insertion_point(field_set:GameProto.RoomInfo.roundTime)
}

// int32 roundNumber = 3;
inline void RoomInfo::clear_roundnumber() {
  roundnumber_ = 0;
}
inline ::google::protobuf::int32 RoomInfo::roundnumber() const {
  // @@protoc_insertion_point(field_get:GameProto.RoomInfo.roundNumber)
  return roundnumber_;
}
inline void RoomInfo::set_roundnumber(::google::protobuf::int32 value) {
  
  roundnumber_ = value;
  // @@protoc_insertion_point(field_set:GameProto.RoomInfo.roundNumber)
}

// string roomName = 4;
inline void RoomInfo::clear_roomname() {
  roomname_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& RoomInfo::roomname() const {
  // @@protoc_insertion_point(field_get:GameProto.RoomInfo.roomName)
  return roomname_.GetNoArena();
}
inline void RoomInfo::set_roomname(const ::std::string& value) {
  
  roomname_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:GameProto.RoomInfo.roomName)
}
#if LANG_CXX11
inline void RoomInfo::set_roomname(::std::string&& value) {
  
  roomname_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:GameProto.RoomInfo.roomName)
}
#endif
inline void RoomInfo::set_roomname(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  roomname_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:GameProto.RoomInfo.roomName)
}
inline void RoomInfo::set_roomname(const char* value, size_t size) {
  
  roomname_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:GameProto.RoomInfo.roomName)
}
inline ::std::string* RoomInfo::mutable_roomname() {
  
  // @@protoc_insertion_point(field_mutable:GameProto.RoomInfo.roomName)
  return roomname_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* RoomInfo::release_roomname() {
  // @@protoc_insertion_point(field_release:GameProto.RoomInfo.roomName)
  
  return roomname_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void RoomInfo::set_allocated_roomname(::std::string* roomname) {
  if (roomname != NULL) {
    
  } else {
    
  }
  roomname_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), roomname);
  // @@protoc_insertion_point(field_set_allocated:GameProto.RoomInfo.roomName)
}

// string mapName = 5;
inline void RoomInfo::clear_mapname() {
  mapname_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& RoomInfo::mapname() const {
  // @@protoc_insertion_point(field_get:GameProto.RoomInfo.mapName)
  return mapname_.GetNoArena();
}
inline void RoomInfo::set_mapname(const ::std::string& value) {
  
  mapname_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:GameProto.RoomInfo.mapName)
}
#if LANG_CXX11
inline void RoomInfo::set_mapname(::std::string&& value) {
  
  mapname_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:GameProto.RoomInfo.mapName)
}
#endif
inline void RoomInfo::set_mapname(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  mapname_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:GameProto.RoomInfo.mapName)
}
inline void RoomInfo::set_mapname(const char* value, size_t size) {
  
  mapname_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:GameProto.RoomInfo.mapName)
}
inline ::std::string* RoomInfo::mutable_mapname() {
  
  // @@protoc_insertion_point(field_mutable:GameProto.RoomInfo.mapName)
  return mapname_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* RoomInfo::release_mapname() {
  // @@protoc_insertion_point(field_release:GameProto.RoomInfo.mapName)
  
  return mapname_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void RoomInfo::set_allocated_mapname(::std::string* mapname) {
  if (mapname != NULL) {
    
  } else {
    
  }
  mapname_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), mapname);
  // @@protoc_insertion_point(field_set_allocated:GameProto.RoomInfo.mapName)
}

// string password = 6;
inline void RoomInfo::clear_password() {
  password_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& RoomInfo::password() const {
  // @@protoc_insertion_point(field_get:GameProto.RoomInfo.password)
  return password_.GetNoArena();
}
inline void RoomInfo::set_password(const ::std::string& value) {
  
  password_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:GameProto.RoomInfo.password)
}
#if LANG_CXX11
inline void RoomInfo::set_password(::std::string&& value) {
  
  password_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:GameProto.RoomInfo.password)
}
#endif
inline void RoomInfo::set_password(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  password_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:GameProto.RoomInfo.password)
}
inline void RoomInfo::set_password(const char* value, size_t size) {
  
  password_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:GameProto.RoomInfo.password)
}
inline ::std::string* RoomInfo::mutable_password() {
  
  // @@protoc_insertion_point(field_mutable:GameProto.RoomInfo.password)
  return password_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* RoomInfo::release_password() {
  // @@protoc_insertion_point(field_release:GameProto.RoomInfo.password)
  
  return password_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void RoomInfo::set_allocated_password(::std::string* password) {
  if (password != NULL) {
    
  } else {
    
  }
  password_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), password);
  // @@protoc_insertion_point(field_set_allocated:GameProto.RoomInfo.password)
}

// int32 maxPlayers = 7;
inline void RoomInfo::clear_maxplayers() {
  maxplayers_ = 0;
}
inline ::google::protobuf::int32 RoomInfo::maxplayers() const {
  // @@protoc_insertion_point(field_get:GameProto.RoomInfo.maxPlayers)
  return maxplayers_;
}
inline void RoomInfo::set_maxplayers(::google::protobuf::int32 value) {
  
  maxplayers_ = value;
  // @@protoc_insertion_point(field_set:GameProto.RoomInfo.maxPlayers)
}

// int32 curPlayerNumber = 8;
inline void RoomInfo::clear_curplayernumber() {
  curplayernumber_ = 0;
}
inline ::google::protobuf::int32 RoomInfo::curplayernumber() const {
  // @@protoc_insertion_point(field_get:GameProto.RoomInfo.curPlayerNumber)
  return curplayernumber_;
}
inline void RoomInfo::set_curplayernumber(::google::protobuf::int32 value) {
  
  curplayernumber_ = value;
  // @@protoc_insertion_point(field_set:GameProto.RoomInfo.curPlayerNumber)
}

// repeated .GameProto.PlayerInfo preparedPlayers = 9;
inline int RoomInfo::preparedplayers_size() const {
  return preparedplayers_.size();
}
inline void RoomInfo::clear_preparedplayers() {
  preparedplayers_.Clear();
}
inline const ::GameProto::PlayerInfo& RoomInfo::preparedplayers(int index) const {
  // @@protoc_insertion_point(field_get:GameProto.RoomInfo.preparedPlayers)
  return preparedplayers_.Get(index);
}
inline ::GameProto::PlayerInfo* RoomInfo::mutable_preparedplayers(int index) {
  // @@protoc_insertion_point(field_mutable:GameProto.RoomInfo.preparedPlayers)
  return preparedplayers_.Mutable(index);
}
inline ::GameProto::PlayerInfo* RoomInfo::add_preparedplayers() {
  // @@protoc_insertion_point(field_add:GameProto.RoomInfo.preparedPlayers)
  return preparedplayers_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::GameProto::PlayerInfo >*
RoomInfo::mutable_preparedplayers() {
  // @@protoc_insertion_point(field_mutable_list:GameProto.RoomInfo.preparedPlayers)
  return &preparedplayers_;
}
inline const ::google::protobuf::RepeatedPtrField< ::GameProto::PlayerInfo >&
RoomInfo::preparedplayers() const {
  // @@protoc_insertion_point(field_list:GameProto.RoomInfo.preparedPlayers)
  return preparedplayers_;
}

// repeated .GameProto.PlayerInfo unPreparedPlayers = 10;
inline int RoomInfo::unpreparedplayers_size() const {
  return unpreparedplayers_.size();
}
inline void RoomInfo::clear_unpreparedplayers() {
  unpreparedplayers_.Clear();
}
inline const ::GameProto::PlayerInfo& RoomInfo::unpreparedplayers(int index) const {
  // @@protoc_insertion_point(field_get:GameProto.RoomInfo.unPreparedPlayers)
  return unpreparedplayers_.Get(index);
}
inline ::GameProto::PlayerInfo* RoomInfo::mutable_unpreparedplayers(int index) {
  // @@protoc_insertion_point(field_mutable:GameProto.RoomInfo.unPreparedPlayers)
  return unpreparedplayers_.Mutable(index);
}
inline ::GameProto::PlayerInfo* RoomInfo::add_unpreparedplayers() {
  // @@protoc_insertion_point(field_add:GameProto.RoomInfo.unPreparedPlayers)
  return unpreparedplayers_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::GameProto::PlayerInfo >*
RoomInfo::mutable_unpreparedplayers() {
  // @@protoc_insertion_point(field_mutable_list:GameProto.RoomInfo.unPreparedPlayers)
  return &unpreparedplayers_;
}
inline const ::google::protobuf::RepeatedPtrField< ::GameProto::PlayerInfo >&
RoomInfo::unpreparedplayers() const {
  // @@protoc_insertion_point(field_list:GameProto.RoomInfo.unPreparedPlayers)
  return unpreparedplayers_;
}

// int32 master = 11;
inline void RoomInfo::clear_master() {
  master_ = 0;
}
inline ::google::protobuf::int32 RoomInfo::master() const {
  // @@protoc_insertion_point(field_get:GameProto.RoomInfo.master)
  return master_;
}
inline void RoomInfo::set_master(::google::protobuf::int32 value) {
  
  master_ = value;
  // @@protoc_insertion_point(field_set:GameProto.RoomInfo.master)
}

// -------------------------------------------------------------------

// ClientMsg

// .GameProto.ClientEventCode type = 1;
inline void ClientMsg::clear_type() {
  type_ = 0;
}
inline ::GameProto::ClientEventCode ClientMsg::type() const {
  // @@protoc_insertion_point(field_get:GameProto.ClientMsg.type)
  return static_cast< ::GameProto::ClientEventCode >(type_);
}
inline void ClientMsg::set_type(::GameProto::ClientEventCode value) {
  
  type_ = value;
  // @@protoc_insertion_point(field_set:GameProto.ClientMsg.type)
}

// .GameProto.PlayerInfo playerinfo = 2;
inline bool ClientMsg::has_playerinfo() const {
  return this != internal_default_instance() && playerinfo_ != NULL;
}
inline void ClientMsg::clear_playerinfo() {
  if (GetArenaNoVirtual() == NULL && playerinfo_ != NULL) {
    delete playerinfo_;
  }
  playerinfo_ = NULL;
}
inline const ::GameProto::PlayerInfo& ClientMsg::playerinfo() const {
  const ::GameProto::PlayerInfo* p = playerinfo_;
  // @@protoc_insertion_point(field_get:GameProto.ClientMsg.playerinfo)
  return p != NULL ? *p : *reinterpret_cast<const ::GameProto::PlayerInfo*>(
      &::GameProto::_PlayerInfo_default_instance_);
}
inline ::GameProto::PlayerInfo* ClientMsg::release_playerinfo() {
  // @@protoc_insertion_point(field_release:GameProto.ClientMsg.playerinfo)
  
  ::GameProto::PlayerInfo* temp = playerinfo_;
  playerinfo_ = NULL;
  return temp;
}
inline ::GameProto::PlayerInfo* ClientMsg::mutable_playerinfo() {
  
  if (playerinfo_ == NULL) {
    playerinfo_ = new ::GameProto::PlayerInfo;
  }
  // @@protoc_insertion_point(field_mutable:GameProto.ClientMsg.playerinfo)
  return playerinfo_;
}
inline void ClientMsg::set_allocated_playerinfo(::GameProto::PlayerInfo* playerinfo) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete playerinfo_;
  }
  if (playerinfo) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      playerinfo = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, playerinfo, submessage_arena);
    }
    
  } else {
    
  }
  playerinfo_ = playerinfo;
  // @@protoc_insertion_point(field_set_allocated:GameProto.ClientMsg.playerinfo)
}

// .GameProto.PlayerInput input = 3;
inline bool ClientMsg::has_input() const {
  return this != internal_default_instance() && input_ != NULL;
}
inline void ClientMsg::clear_input() {
  if (GetArenaNoVirtual() == NULL && input_ != NULL) {
    delete input_;
  }
  input_ = NULL;
}
inline const ::GameProto::PlayerInput& ClientMsg::input() const {
  const ::GameProto::PlayerInput* p = input_;
  // @@protoc_insertion_point(field_get:GameProto.ClientMsg.input)
  return p != NULL ? *p : *reinterpret_cast<const ::GameProto::PlayerInput*>(
      &::GameProto::_PlayerInput_default_instance_);
}
inline ::GameProto::PlayerInput* ClientMsg::release_input() {
  // @@protoc_insertion_point(field_release:GameProto.ClientMsg.input)
  
  ::GameProto::PlayerInput* temp = input_;
  input_ = NULL;
  return temp;
}
inline ::GameProto::PlayerInput* ClientMsg::mutable_input() {
  
  if (input_ == NULL) {
    input_ = new ::GameProto::PlayerInput;
  }
  // @@protoc_insertion_point(field_mutable:GameProto.ClientMsg.input)
  return input_;
}
inline void ClientMsg::set_allocated_input(::GameProto::PlayerInput* input) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete input_;
  }
  if (input) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      input = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, input, submessage_arena);
    }
    
  } else {
    
  }
  input_ = input;
  // @@protoc_insertion_point(field_set_allocated:GameProto.ClientMsg.input)
}

// .GameProto.RoomInfo roominfo = 4;
inline bool ClientMsg::has_roominfo() const {
  return this != internal_default_instance() && roominfo_ != NULL;
}
inline void ClientMsg::clear_roominfo() {
  if (GetArenaNoVirtual() == NULL && roominfo_ != NULL) {
    delete roominfo_;
  }
  roominfo_ = NULL;
}
inline const ::GameProto::RoomInfo& ClientMsg::roominfo() const {
  const ::GameProto::RoomInfo* p = roominfo_;
  // @@protoc_insertion_point(field_get:GameProto.ClientMsg.roominfo)
  return p != NULL ? *p : *reinterpret_cast<const ::GameProto::RoomInfo*>(
      &::GameProto::_RoomInfo_default_instance_);
}
inline ::GameProto::RoomInfo* ClientMsg::release_roominfo() {
  // @@protoc_insertion_point(field_release:GameProto.ClientMsg.roominfo)
  
  ::GameProto::RoomInfo* temp = roominfo_;
  roominfo_ = NULL;
  return temp;
}
inline ::GameProto::RoomInfo* ClientMsg::mutable_roominfo() {
  
  if (roominfo_ == NULL) {
    roominfo_ = new ::GameProto::RoomInfo;
  }
  // @@protoc_insertion_point(field_mutable:GameProto.ClientMsg.roominfo)
  return roominfo_;
}
inline void ClientMsg::set_allocated_roominfo(::GameProto::RoomInfo* roominfo) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete roominfo_;
  }
  if (roominfo) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      roominfo = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, roominfo, submessage_arena);
    }
    
  } else {
    
  }
  roominfo_ = roominfo;
  // @@protoc_insertion_point(field_set_allocated:GameProto.ClientMsg.roominfo)
}

// -------------------------------------------------------------------

// ServerMsg

// .GameProto.ServerEventCode type = 1;
inline void ServerMsg::clear_type() {
  type_ = 0;
}
inline ::GameProto::ServerEventCode ServerMsg::type() const {
  // @@protoc_insertion_point(field_get:GameProto.ServerMsg.type)
  return static_cast< ::GameProto::ServerEventCode >(type_);
}
inline void ServerMsg::set_type(::GameProto::ServerEventCode value) {
  
  type_ = value;
  // @@protoc_insertion_point(field_set:GameProto.ServerMsg.type)
}

// int32 fid = 2;
inline void ServerMsg::clear_fid() {
  fid_ = 0;
}
inline ::google::protobuf::int32 ServerMsg::fid() const {
  // @@protoc_insertion_point(field_get:GameProto.ServerMsg.fid)
  return fid_;
}
inline void ServerMsg::set_fid(::google::protobuf::int32 value) {
  
  fid_ = value;
  // @@protoc_insertion_point(field_set:GameProto.ServerMsg.fid)
}

// string str = 3;
inline void ServerMsg::clear_str() {
  str_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& ServerMsg::str() const {
  // @@protoc_insertion_point(field_get:GameProto.ServerMsg.str)
  return str_.GetNoArena();
}
inline void ServerMsg::set_str(const ::std::string& value) {
  
  str_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:GameProto.ServerMsg.str)
}
#if LANG_CXX11
inline void ServerMsg::set_str(::std::string&& value) {
  
  str_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:GameProto.ServerMsg.str)
}
#endif
inline void ServerMsg::set_str(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  str_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:GameProto.ServerMsg.str)
}
inline void ServerMsg::set_str(const char* value, size_t size) {
  
  str_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:GameProto.ServerMsg.str)
}
inline ::std::string* ServerMsg::mutable_str() {
  
  // @@protoc_insertion_point(field_mutable:GameProto.ServerMsg.str)
  return str_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* ServerMsg::release_str() {
  // @@protoc_insertion_point(field_release:GameProto.ServerMsg.str)
  
  return str_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void ServerMsg::set_allocated_str(::std::string* str) {
  if (str != NULL) {
    
  } else {
    
  }
  str_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), str);
  // @@protoc_insertion_point(field_set_allocated:GameProto.ServerMsg.str)
}

// .GameProto.PlayerInfo playerInfo = 4;
inline bool ServerMsg::has_playerinfo() const {
  return this != internal_default_instance() && playerinfo_ != NULL;
}
inline void ServerMsg::clear_playerinfo() {
  if (GetArenaNoVirtual() == NULL && playerinfo_ != NULL) {
    delete playerinfo_;
  }
  playerinfo_ = NULL;
}
inline const ::GameProto::PlayerInfo& ServerMsg::playerinfo() const {
  const ::GameProto::PlayerInfo* p = playerinfo_;
  // @@protoc_insertion_point(field_get:GameProto.ServerMsg.playerInfo)
  return p != NULL ? *p : *reinterpret_cast<const ::GameProto::PlayerInfo*>(
      &::GameProto::_PlayerInfo_default_instance_);
}
inline ::GameProto::PlayerInfo* ServerMsg::release_playerinfo() {
  // @@protoc_insertion_point(field_release:GameProto.ServerMsg.playerInfo)
  
  ::GameProto::PlayerInfo* temp = playerinfo_;
  playerinfo_ = NULL;
  return temp;
}
inline ::GameProto::PlayerInfo* ServerMsg::mutable_playerinfo() {
  
  if (playerinfo_ == NULL) {
    playerinfo_ = new ::GameProto::PlayerInfo;
  }
  // @@protoc_insertion_point(field_mutable:GameProto.ServerMsg.playerInfo)
  return playerinfo_;
}
inline void ServerMsg::set_allocated_playerinfo(::GameProto::PlayerInfo* playerinfo) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete playerinfo_;
  }
  if (playerinfo) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      playerinfo = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, playerinfo, submessage_arena);
    }
    
  } else {
    
  }
  playerinfo_ = playerinfo;
  // @@protoc_insertion_point(field_set_allocated:GameProto.ServerMsg.playerInfo)
}

// int32 framID = 5;
inline void ServerMsg::clear_framid() {
  framid_ = 0;
}
inline ::google::protobuf::int32 ServerMsg::framid() const {
  // @@protoc_insertion_point(field_get:GameProto.ServerMsg.framID)
  return framid_;
}
inline void ServerMsg::set_framid(::google::protobuf::int32 value) {
  
  framid_ = value;
  // @@protoc_insertion_point(field_set:GameProto.ServerMsg.framID)
}

// repeated .GameProto.PlayerInput inputs = 6;
inline int ServerMsg::inputs_size() const {
  return inputs_.size();
}
inline void ServerMsg::clear_inputs() {
  inputs_.Clear();
}
inline const ::GameProto::PlayerInput& ServerMsg::inputs(int index) const {
  // @@protoc_insertion_point(field_get:GameProto.ServerMsg.inputs)
  return inputs_.Get(index);
}
inline ::GameProto::PlayerInput* ServerMsg::mutable_inputs(int index) {
  // @@protoc_insertion_point(field_mutable:GameProto.ServerMsg.inputs)
  return inputs_.Mutable(index);
}
inline ::GameProto::PlayerInput* ServerMsg::add_inputs() {
  // @@protoc_insertion_point(field_add:GameProto.ServerMsg.inputs)
  return inputs_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::GameProto::PlayerInput >*
ServerMsg::mutable_inputs() {
  // @@protoc_insertion_point(field_mutable_list:GameProto.ServerMsg.inputs)
  return &inputs_;
}
inline const ::google::protobuf::RepeatedPtrField< ::GameProto::PlayerInput >&
ServerMsg::inputs() const {
  // @@protoc_insertion_point(field_list:GameProto.ServerMsg.inputs)
  return inputs_;
}

// repeated .GameProto.PlayerState states = 7;
inline int ServerMsg::states_size() const {
  return states_.size();
}
inline void ServerMsg::clear_states() {
  states_.Clear();
}
inline const ::GameProto::PlayerState& ServerMsg::states(int index) const {
  // @@protoc_insertion_point(field_get:GameProto.ServerMsg.states)
  return states_.Get(index);
}
inline ::GameProto::PlayerState* ServerMsg::mutable_states(int index) {
  // @@protoc_insertion_point(field_mutable:GameProto.ServerMsg.states)
  return states_.Mutable(index);
}
inline ::GameProto::PlayerState* ServerMsg::add_states() {
  // @@protoc_insertion_point(field_add:GameProto.ServerMsg.states)
  return states_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::GameProto::PlayerState >*
ServerMsg::mutable_states() {
  // @@protoc_insertion_point(field_mutable_list:GameProto.ServerMsg.states)
  return &states_;
}
inline const ::google::protobuf::RepeatedPtrField< ::GameProto::PlayerState >&
ServerMsg::states() const {
  // @@protoc_insertion_point(field_list:GameProto.ServerMsg.states)
  return states_;
}

// repeated .GameProto.RoomInfo roominfos = 8;
inline int ServerMsg::roominfos_size() const {
  return roominfos_.size();
}
inline void ServerMsg::clear_roominfos() {
  roominfos_.Clear();
}
inline const ::GameProto::RoomInfo& ServerMsg::roominfos(int index) const {
  // @@protoc_insertion_point(field_get:GameProto.ServerMsg.roominfos)
  return roominfos_.Get(index);
}
inline ::GameProto::RoomInfo* ServerMsg::mutable_roominfos(int index) {
  // @@protoc_insertion_point(field_mutable:GameProto.ServerMsg.roominfos)
  return roominfos_.Mutable(index);
}
inline ::GameProto::RoomInfo* ServerMsg::add_roominfos() {
  // @@protoc_insertion_point(field_add:GameProto.ServerMsg.roominfos)
  return roominfos_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::GameProto::RoomInfo >*
ServerMsg::mutable_roominfos() {
  // @@protoc_insertion_point(field_mutable_list:GameProto.ServerMsg.roominfos)
  return &roominfos_;
}
inline const ::google::protobuf::RepeatedPtrField< ::GameProto::RoomInfo >&
ServerMsg::roominfos() const {
  // @@protoc_insertion_point(field_list:GameProto.ServerMsg.roominfos)
  return roominfos_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace GameProto

namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::GameProto::ServerEventCode> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::GameProto::ServerEventCode>() {
  return ::GameProto::ServerEventCode_descriptor();
}
template <> struct is_proto_enum< ::GameProto::ClientEventCode> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::GameProto::ClientEventCode>() {
  return ::GameProto::ClientEventCode_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_game_5fproto_2eproto__INCLUDED
